### ISSUE TITLE
Running orf_search.py --test in conda fails

### ISSUE THREAD

**Issue by zinfin** [ablab/orf-search#2]
Activating the newly created orf_search conda environment and running `orf_search.py --test` to check for correct installation results in the following error:
```
INFO     [2023-04-11 16:30:04,910] Start test on a small dataset...
INFO     [2023-04-11 16:30:04,916] Running HMM alignment. See log in tiny_dataset_test/ricinb_lectin2.log
DEBUG    [2023-04-11 16:30:04,916] Running: /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/aligners/pathracer /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/ricinb_lectin2.hmm /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/graph.gfa 55 --output tiny_dataset_test/ricinb_lectin2 --rescore --annotate-graph --threads 1 -E 1e-09 --domE 1e-09 --max-size 2500000 > tiny_dataset_test/ricinb_lectin2.log
INFO     [2023-04-11 16:30:04,960] Running Start Codon Distance Estimator. See log in tiny_dataset_test/ricinb_lectin2_true.log
DEBUG    [2023-04-11 16:30:04,961] Running: hmmsearch --domtblout tiny_dataset_test/ricinb_lectin2.dtbl -E 1e-09 --cpu 1 /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/ricinb_lectin2.hmm /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/toxin.fasta > tiny_dataset_test/ricinb_lectin2_true.log
INFO     [2023-04-11 16:30:04,968] Running Sequence Alignment. See log in /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/toxin.fasta.log
DEBUG    [2023-04-11 16:30:04,969] Running: /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/aligners/spaligner /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/aligners/spaligner_cfg.yaml -g /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/graph.gfa -k 55 -s /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/toxin.fasta -t 1 -d protein -o /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/toxin.fasta > /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/toxin.fasta.log
INFO     [2023-04-11 16:30:05,016] Extracting ORFs from assembly graph. See log in tiny_dataset_test/orfs_raw.log
DEBUG    [2023-04-11 16:30:05,016] Running: python /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/scripts/identify_gene_ends.py  -m tiny_dataset_test/ricinb_lectin2 -p /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/toxin.fasta -d tiny_dataset_test/ricinb_lectin2.dtbl -g /data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/tiny_dataset/graph.gfa -k 55 -t 1 -o tiny_dataset_test
Traceback (most recent call last):
  File "/data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/orf_search/scripts/identify_gene_ends.py", line 3, in <module>
    from Bio.Alphabet import generic_dna
  File "/data1/mambaforge/envs/orf_search/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
ERROR    [2023-04-11 16:30:05,076] Orfs generation failed
```

**Comment by TanyaDvorkina** [comment]
Hi,

Thank you for using ORFograph! 

Please try to reinstall the release of conda orf-search. I fixed the issue.

If you have any other questions or problems while using ORFograph, please don't hesitate to ask.

**Comment by zinfin** [comment]
Thanks for the fix! Tests now work as expected!
